### ISSUE TITLE
Provide example app with Code Mirror and Camel LSP

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-codemirror#1]
based on https://github.com/wylieconlon/lsp-editor-adapter

see example fo rother languages https://github.com/wylieconlon/lsp-editor-adapter/tree/master/example

requires support of websocket connection in Camel LSP https://github.com/camel-tooling/camel-language-server/issues/260

**Comment by djelinek** [comment]
verified with GitHub codemirror example and locally started LSP server with --websocket parameter

**Comment by djelinek** [comment]
verified with GitHub codemirror example and locally started LSP server with --websocket parameter
